config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :games
  resources :benches, :path => "benchmarks" do
    collection do
      match 'stats' => 'benches#stats', via: [:get, :post], as: :stats
    end
  end
  resources :runs
  resources :traces do
    collection do
      match 'line_chart_amount' => 'traces#line_chart_amount', via: [:get], as: :line_chart_amount
    end
    member do
      get 'execution_time'
      get 'frames/:frame_id', to: 'traces#frames'
      post 'frames/:frame_id', to: 'traces#frames'
    end
    resources :trace_frames do
      resources :frame_outputs
    end
  end
  resources :static, only: [:index] do
    collection do
      get 'get_url'
      get 'get_ref_frames'
      post 'get_ref_frames'
    end
  end
  resources :users, only: [:edit, :show, :update, :index] do
    member do
      get 'edit_permissions'
    end
  end
  resources :gpus do
    member do
      get 'gpu_frames'
      get 'execution_time'
    end
    resources :frame_outputs
  end
  resources :frame_outputs do
    member do
      get 'history', to: 'frame_outputs#history'
    end
  end
  resources :games_tags, only: [:destroy]
  resources :bugs, only: [:create, :destroy, :index, :show, :update, :new] do
    member do
      post 'associate'
      post 'mark_fixed'
      post 're_open'
      get 'create_upstream_issue'
    end
    collection do
      match 'line_chart_amount' => 'bugs#line_chart_amount', via: [:get], as: :line_chart_amount
    end
  end
  resources :bugs_trace_frames, only: [:destroy]
  resources :jobs, only: [:destroy, :index, :show]
  resources :deduped_frame_outputs do
    member do
      post 'acceptable_frame'
      post 'unacceptable_frame'
      get 'frame_bug'
      get 'pre_merge_frame_bug'
      get 'issue'
      get 'next_frame'
      post 'dissociate'
    end
  end
  match 'stats' => 'static#stats', via: [:get], as: :stats
  resources :trace_execs
  resources :providers, only: [:destroy]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :graphics_apis
      match 'checksum' => 'static#checksum', via: [:get, :post], as: :checksum
      match 'image_checksum' => 'static#image_checksum', via: [:get, :post], as: :image_checksum
      match 'unoptimized_traces' => 'static#unoptimized_traces', via: [:get, :post], as: :unoptimized_traces
      match 'trace_lock' => 'static#trace_lock', via: [:get, :post], as: :trace_lock
      match 'frames_needing_review' => 'static#frames', via: [:get], as: :frames
      devise_scope :user do
        post 'login', to: 'sessions#create'
      end
      resources :traces do
        collection do
          match 'enrollment' => 'traces#enrollment', via: [:get], as: :enrollment
        end
      end
      resources :games
      resources :runs
      resources :jobs do
        resources :trace_execs
      end
      resources :trace_execs
      resources :gpus
      resources :users, only: [:index]
      resources :trace_compatibilities
      resources :commits
      resources :projects
      resources :benches
      resources :stats do
        collection do
          match 'frame_outputs' => 'stats#frame_outputs', via: [:get, :post], as: :frame_outputs
          get 'trace_frames/:id/' => 'stats#trace_frames', via: [:get], as: :trace_frames
          get 'blobs/:id/' => 'stats#blobs', via: [:get], as: :blobs
        end
      end
      resources :deduped_frame_outputs
    end
  end
  match "/-/profile", to: "users#profile", via: [:get], as: :profile
  match 'frames_needing_review' => 'static#frames', via: [:get], as: :frames
  match 'gpu_frames' => 'static#gpu_frames', via: [:get, :post], as: :gpu_frames
  root 'static#index'
end

app/models/job.rb
class Job < ApplicationRecord
    has_many :trace_execs, -> { distinct }, dependent: :destroy
    has_many :traces, -> { distinct  }, through: :trace_execs
    has_many :graphics_apis, -> { distinct  }, through: :traces
    has_many :gpus, -> { distinct }, through: :trace_execs
    has_many :frame_outputs, -> { distinct  }, through: :trace_execs
    has_many :deduped_frame_outputs, -> { distinct }, through: :frame_outputs
    has_many :bugs, -> { distinct }, through: :deduped_frame_outputs
    has_many :jobs, -> { distinct }, through: :deduped_frame_outputs
    has_many :driver_versions, -> { distinct }, through: :trace_execs
    has_many :driver_branches, -> { distinct }, through: :driver_versions
    has_many :drivers, -> { distinct }, through: :driver_branches
    has_many :blobs, -> { select(:id, :filename, :service_name).distinct}, through: :traces
    has_many :trace_frames, through: :traces
    belongs_to :user
    belongs_to :timeline, foreign_key: :timeline_id, class_name: 'JobTimeLine'

    def next_in_timeline
        Job.where(timeline: self.timeline).where("id > ?", self.id).first
    end
    
    def prev_in_timeline
        Job.where(timeline: self.timeline).where("id < ?", self.id).last
    end
end

app/controllers/api/v1/jobs_controller.rb
module Api
    module V1
        class JobsController < ApplicationController
            skip_forgery_protection
            before_action :authenticate_user!, except: [:index]
            before_action :admin, except: [:index]

            def index
                @jobs = Job.all
                if params[:name]
                    render json: Job.find_by(name: params[:name])
                else
                    respond_to do |f|
                        f.json
                    end
                end
            end

            def create
                @job = Job.new(job_params)
                @job.user = current_user
                @job_existing = Job.find_by(name: @job.name)
                if @job_existing
                    render json: @job_existing
                else
                # assign timeline
                    if params[:job_timeline]
                        @timeline = JobTimeLine.find_or_create_by(project: params[:job_timeline][:project],
                                                                branch: params[:job_timeline][:branch])
                        @timeline.update(project_url: params[:job_timeline][:project_url],
                                        base_url_for_commits: params[:job_timeline][:base_url_for_commits])
                        @job.timeline_id = @timeline.id
                    end
                    @job.save
                    if @job.errors.any?
                        render json: @job.errors
                    else
                        render json: @job
                    end
                end
            end

            private
            def job_params
                params.require(:job).permit(:gpu_id, :user_id, :name, :is_released_code, :commit_version, metadata: {})
            end

        end
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
    before_action :can_review_frames, except: [:show, :index, :destroy]
    before_action :admin, only: [:destroy]
    before_action :authenticate_user!, except: [:show, :index]

    class ExecTimeStats < Struct.new(:min, :max, :avg, :sample_count)
        def interval
            return self.max - self.min
        end

        def sample_difference_percentage(execution_time)
            (((execution_time / self.avg) * 100.0) - 100).to_f
        end

        def is_sample_within_variance(exec_time)
            safety_margin = ((self.interval / 2) * 1.2)
            return (exec_time >= (self.min - safety_margin)) && (exec_time <= (self.max + safety_margin))
        end

        def to_s
            "#{self.avg.round(1)} ±#{(self.interval / 2).round(1)}"
        end
    end

    def index
        @q = Job.ransack(params[:q])
        @jobs = @q.result.order(id: :desc).page(params[:page]).per(10)
    end

    def show
        @job = Job.find(params[:id])
        @codenames = Hash.new { |h, k| h[k] = Hash.new(&h.default_proc) }
        @execs = Hash.new { |h, k| h[k] = Hash.new(&h.default_proc) }
        @filenames = Hash.new { |h, k| h[k] = Hash.new(&h.default_proc) }
        @trace_exec_history = Hash.new { |h, k| h[k] = Hash.new(&h.default_proc) }
        @frame_outputs = @job.frame_outputs
        @codenames = Gpu.codenames
        
        threads = []

        threads << Thread.new {
            @dedup_released = Set.new(@frame_outputs.includes(:job).where(job: {is_released_code: true}).pluck(:deduped_frame_output_id))
            @job.blobs.includes(:attachments).pluck('active_storage_attachments.record_id', :filename).each do |blob|
                @filenames[blob[0]] = blob[1]
            end
        }

        threads << Thread.new {
            @frames = @frame_outputs.includes(:trace_exec, :trace_frame, :trace, :gpu,
            :deduped_frame_output, :bugs, trace_exec: [driver_version: [driver_branch: [:driver]]],
            trace: :upload_blob).where(deduped_frame_output: {is_acceptable: [nil, false]}).
            select(:trace_exec_id, :trace_frame_id, :deduped_frame_output_id)
        }

        @trace_execs = @job.trace_execs
        threads << Thread.new {
            prev_job_created_at = Job.where("id < ?", @job.id).last.created_at
            last_jobs_in_timeline = Job.where(timeline: @job.timeline, is_released_code: true, created_at: Date.new..prev_job_created_at).last(20).pluck(:id)
            TraceExec.includes(:job, :gpu, :trace).where(gpu: @job.gpus, trace: @job.traces, status: 0, job: {id: last_jobs_in_timeline}).
                where('execution_time > ?', 0).where.not(id: @job.trace_execs.pluck(:id)).order(id: :desc).pluck(:trace_id, :gpu_id, :driver_version_id, :execution_time).each do |exec_|
                    trace_id = exec_[0]
                    gpu_id = exec_[1]
                    driver_version_id = exec_[2]
                    execution_time = exec_[3]
                    if @trace_exec_history[trace_id][gpu_id][driver_version_id].size == 0
                        @trace_exec_history[trace_id][gpu_id][driver_version_id] = [execution_time]
                    elsif @trace_exec_history[trace_id][gpu_id][driver_version_id].size < 10
                        @trace_exec_history[trace_id][gpu_id][driver_version_id].append(execution_time)
                    end
                end
                
                @trace_exec_history.each do |trace_id, exec_history|
                    exec_history.each do |gpu_id, exec_history|
                        exec_history.each do |driver_version_id, exec_history|
                            @trace_exec_history[trace_id][gpu_id][driver_version_id] = ExecTimeStats.new(exec_history.min, exec_history.max, exec_history.sum / exec_history.size, exec_history.size)
                        end
                    end
                end
        }
        threads << Thread.new {
            @columns = SortedSet.new()
            @unknown = GraphicsApi.new(id: nil, name: "Unknown")
            @trace_execs.includes(:driver, :graphics_api, :trace, :gpu, :trace, driver_version: [driver_branch: [:driver]]).each do |exec_|
                @columns << ExecColumn.new(@codenames[exec_.gpu_id], exec_.gpu, exec_.driver_version)
                if exec_.graphics_api == nil
                    @execs[@unknown][exec_.trace_id][exec_.gpu_id][exec_.driver_version][exec_] = nil
                else
                    @execs[exec_.graphics_api][exec_.trace_id][exec_.gpu_id][exec_.driver_version][exec_] = nil
                end
            end
        }

        threads.each(&:join)
    end

    def destroy
        @job = Job.find(params[:id])
        @job.destroy
        DedupedFrameOutput.left_joins(:frame_outputs).where(frame_outputs: {id: nil}).destroy_all
        redirect_to jobs_path
    end

    # private
    # def job_params
    #     params.require(:job).permit(:gpu_id, :user_id, metadata: {})
    # end

end

app/views/jobs/_commit.html.erb
<% if job.commit_version %>
    <!-- Commit: <%= link_to job.commit_version, job.timeline.base_url_for_commits + job.commit_version %> -->
    <% prev_job = job.prev_in_timeline %>
    <% if prev_job && prev_job.commit_version && job.timeline.url_for_comparing_commits %>
        Commits: <%= link_to prev_job.commit_version + "..." + job.commit_version,
            job.timeline.url_for_comparing_commits + prev_job.commit_version +
            "..." + job.commit_version, target: :_blank %>
    <% end %>
<% end %>

app/views/jobs/_executions.html.erb
<div class="row">
  <div class="col-sm-12 p-3">
  <% @execs.each do |api| %>
    <% api = api[0] %>
      <h4><%= api.name %></h4>
      <table class="table table-bordered">
        <thead>
        <tr class="text-center">
          <th></th>
          <% last_codename = "" %>
          <% @columns.each do |column| %>
            <% if column.codename != last_codename %>
            <th colspan="<%= @columns.count {|col| col.include? column.codename} %>">
              <%= column.codename %>
            </th>
            <% end %>
            <% last_codename = column.codename %>
          <% end %>
        </tr>
        <tr class="text-center">
          <th></th>
          <% last_gpu = "" %>
          <% @columns.each do |column| %>
            <% if column.gpu != last_gpu %>
            <th colspan="<%= @columns.count {|col| col.include? column.gpu} %>">
              <%= column.gpu.pciid %>
            </th>
            <% end %>
            <% last_gpu = column.gpu %>
          <% end %>
        </tr>
        <tr class="text-center">
          <th>Trace name</th>
          <% @columns.each do |column| %>
            <th>
            <% if column.driver_version %>
              <% if column.driver_version.name.nil? %>
                Unknown driver
              <% else %>
                <%= column.driver_version.driver.name %> 
              <% end %>
              <%= column.driver_version.name %>
            <% else %>
              Unknown driver
            <% end %>
            </th>
          <% end %>
        </tr>
        </thead>
        <tbody>
        <% @execs[api].each do |trace| %>
          <% trace = trace[0] %>
          <tr>
            <td class="text-center"><%= @filenames[trace] %></td>
            <% @columns.each do |column| %>
              <td class="text-center">
                <% @execs[api][trace][column.gpu.id][column.driver_version].each do |exec_| %>
                  <% exec_ = exec_[0] %>
                  <%= link_to exec_ do %>
                    <% if exec_.status == nil || exec_.status > 0 %>
                      <span class="badge badge-danger">crash</span></h1>
                    <% else %>
                      <span class="badge badge-success">complete</span></h1>                            
                    <% end %>
                  <% end %>
                <% end %>
              </td>
            <% end %>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

app/views/jobs/_need_review.html.erb
<% @job.traces.includes(:upload_blob).order('upload_blob.filename').each do |trace| %>
    <ul>
    <% deduped_outputs = trace.deduped_frame_outputs.includes(:jobs).where(jobs: {id: @job.id}) %>
        <% if deduped_outputs.where(is_acceptable: nil).any? %>
            <li><%= render partial: 'traces/trace_link', locals: {trace: trace} %></li>
            <ul>
                <% trace.trace_frames.each do |trace_frame| %>
                    <% if deduped_outputs.where(trace_frame: trace_frame, is_acceptable: nil).any? %>
                        <li><%= trace_frame.frame_id %></li>
                        <ul>
                            <% dedupes = DedupedFrameOutput.includes(:jobs, :trace_frame, :gpus).where(is_acceptable: nil, jobs: {id: @job.id}, trace_frame: {id: trace_frame.id}) %>
                            <li>
                            <% dedupes.each do |frame| %>
                                <% frame.gpus.each do |gpu| %>
                                    <%= deduped_preview(frame, gpu.codename, deduped_frame_output_path(frame.deduped_frame_output)) %>
                                <% end %>
                            <% end %>
                            </li>
                        </ul>
                    <% end %>
                <% end %>
            </ul>
        <% end %>
    </ul>
<% end %>

app/views/jobs/_pre_merge.html.erb
<div class="card collapsed-card">
    <div class="card-header accordion-button" >
        <h3 class="card-title">Job Information</h3>
        <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="collapse"><i class="fas fa-plus"></i></button>
        </div>
    </div>
    <div class="card-body">
        Created at: <%= @job.created_at.strftime("%Y-%m-%d %H:%M:%S") %></br>
        Project: <%= link_to @job.timeline.project, @job.timeline.project_url %></br>
        Branch: <%= link_to @job.timeline.branch, @job.timeline.project_url.match(".*\/").to_s + @job.timeline.branch %></br>
        <%= render partial: 'commit', locals: {job: @job} %></br>
        <% if @job.next_in_timeline != nil && @job.prev_in_timeline != nil %>
            Next job: <%= link_to @job.prev_in_timeline.name, @job.next_in_timeline %></br>
        <% end %>
        <% if @job.prev_in_timeline != nil && @job.next_in_timeline != nil %>
            Previous job: <%= link_to @job.prev_in_timeline.name, @job.prev_in_timeline %>
        <% end %>
    </div>
</div>

<h2>List of frames needing review <span id="needing_review_tooltip" data-toggle="tooltip" data-html="true" title="These are the frames that have never been seen before in a post-merge run, and thus are likely due to changes in rendering coming from your patch set. It is however possible that these frames are never producing a stable output on this particular GPU. Consult mupuf / Martin Roukala if you need more help."><i class="fas fa-question"></i></span></h2>
<div class="card">
    <div class="card-body p-0" id="needing-review">
      <%= render partial: 'regressions', locals: {bool: nil, seen: [@job.is_released_code]} %>
    </div>
</div>

<% unless @job.is_released_code %>
    <h2>List of already-known but un-reviewed frames <span id="known_review_tooltip" data-toggle="tooltip" data-html="true" title="The frames have already been seen in a post-merge run. This means that your patchset is not responsible for it, and thus you are not on the hook for reviewing them. These frames are there so that developers can see which games could potentially be broken without anyone knowing."><i class="fas fa-question"></i></span></h2>
    <div class="card">
        <div class="card-body p-0" id="needing-review">
        <%= render partial: 'regressions', locals: {bool: nil, seen: [true]} %>
        </div>
    </div>
<% end %>

<h2>List of unacceptable frames</h2>
<div class="card">
    <div class="card-body p-0" id="failures">
        <%= render partial: 'regressions', locals: {bool: false, seen: [false, true]} %>
    </div>
</div>
<div class="row">

<h2>Trace runtime changes</h2> <h6 style="padding-top:15px;">&nbsp;(lower is better)</h6>
</div>
<div class="card">
    <div class="card-body p-0">
    <table class="table" data-sortable>
        <thead>
            <tr>
                <th>Trace</th>
                <th>GPU Codename</th>
                <th>Driver Version</th>
                <th>Execution Time</th>
                <th data-sorted="true" data-sorted-direction="descending">Change (%)</th>
            </tr>
        </thead>
        <tbody>
            <% @job.trace_execs.includes(:gpu, :trace, :driver_version, trace: [:upload_blob]).where(status: 0).where('execution_time > ?', 0).
            order('upload_blob.filename').each do |exec_| %>
                <% exec_history = @trace_exec_history[exec_.trace.id][exec_.gpu.id][exec_.driver_version.id] %>
                <% if exec_history != {} && !exec_history.is_sample_within_variance(exec_.execution_time) %>
                    <tr>
                        <td><%= link_to @filenames[exec_.trace.id], exec_.trace %></td>
                        <td><%= link_to @codenames[exec_.gpu.id], exec_.gpu %></td>
                        <td><%= exec_.driver_version %></td>
                        <td>
                            <% tooltip = "min=#{exec_history.min.round(1)}, #{exec_history.max.round(1)}, n=#{exec_history.sample_count}" %>
                            <span title="<%= tooltip %>"><%= exec_history %></span> ->
                            <%= link_to exec_.execution_time.to_s + " s", exec_ %>
                        </td>
                        <% percentage = exec_history.sample_difference_percentage(exec_.execution_time).round(1) %>
                        <td data-value="<%= percentage %>">
                            <span class="<%= percentage.negative? ? "text-success" : "text-danger" %>">
                            <%= percentage.negative? ? percentage : "+" + percentage.to_s %>%</span>
                        </td>
                    </tr>
                <% end %>
            <% end %>
        </tbody>
    </table>
    </div>
</div>

<h2>Trace Executions</h2>
<div class="card">
    <div class="card-body p-0" id="executions">
        <%= render 'executions' %>
    </div>
</div>

<script>
    $('#needing_review_tooltip').tooltip();
    $('#known_review_tooltip').tooltip();
</script>

app/views/jobs/_regressions.html.erb
<% frames = Hash.new { |h, k| h[k] = Hash.new(&h.default_proc) } %>
<% @frames.each do |frame| %>
    <% if frame.deduped_frame_output.is_acceptable == bool %>
        <% if seen.include? (@dedup_released.include? frame.deduped_frame_output.id) %>
            <% frames[frame.trace.id][frame.trace_frame][frame.trace_exec.driver_version][frame.gpu.id][frame] = frame %>
        <% end %>
    <% end %>
<% end %>
<% if frames.empty? %>
No frames to see!
<% end %>
<% frames.each do |trace| %>
    <% trace = trace[0] %>
    <ul>
        <li><%= link_to @filenames[trace], trace_path(trace) %></li>
        <ul>
            <% frames[trace].each do |trace_frame| %>
                <% trace_frame = trace_frame[0] %>
                <li><%= trace_frame.frame_id %></li>
                <ul>
                    <% frames[trace][trace_frame].each do |driver_version| %>
                        <% driver_version = driver_version[0] %>
                        <li>
                            <%= driver_version.driver_branch.driver.name if driver_version %> <%= driver_version.name if driver_version %>: 
                            <% frames[trace][trace_frame][driver_version].each do |gpu| %>
                                <% gpu = gpu[0] %>
                                <% frames[trace][trace_frame][driver_version][gpu].each do |frame| %>
                                    <% frame = frame[0] %>
                                    <%= deduped_preview(frame, @codenames[gpu], deduped_frame_output_path(frame.deduped_frame_output)) %>
                                    <% if bool == false %>
                                        <% frame.bugs.each do |bug| %>
                                            (<%= link_to "bug", bug.issue_url %> <%= link_to "#" + bug.id.to_s, bug %>)
                                        <% end %>
                                    <% end %>
                                <% end %>
                            <% end %>
                        </li>
                    <% end %>
                </ul>
            <% end %>
        </ul>
    </ul>
<% end %>

app/views/jobs/_table.html.erb
<div class="row">
  <div class="col-sm-12">
    <table class="table table-bordered">
      <thead>
        <th>#</th>
        <th>Name</th>
        <th>Released code?</th>
        <th>Trace Executions</th>
        <th>Frames needing review</th>
        <th>Tools</th>
      </thead>
      <tbody>
      <% @jobs.each do |job| %>
        <tr>
          <td><%= link_to job.id, job %></td>
          <td><%= job.name %></td>
          <td>
            <% if job.is_released_code %>
              Post-merge
            <% else %>
              Pre-merge
            <% end %>
          </td>
          <td><%= job.trace_execs.size %></td>
          <td><%= job.frame_outputs.includes(:deduped_frame_output, :job).where(deduped_frame_output: { is_acceptable: nil}, jobs: { is_released_code: job.is_released_code }).size %></td>
          <td>
            <%= link_to "Destroy",
            job_path(job),
            :method => :delete,
            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
            :class => 'btn btn-sm btn-danger', remote: false if current_user && current_user.admin? %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/jobs/index.html.erb
<% content_for(:tabtitle, "Jobs - Valve Dashboard") %>
<% content_for :title do %> Jobs <% end %>
<% JobTimeLine.includes(:jobs).where(jobs: {is_released_code: true}).select(:project, :branch).uniq.each do |timeline| %>
  <%= link_to "[#{timeline.project} - #{timeline.branch}]",
      jobs_path + "?q[timeline_project_cont]=#{timeline.project}&q[timeline_branch_cont]=#{timeline.branch}" , class: 'btn btn-primary' %>
<% end %>
</p>
<div class="card">
    <div class="card-body p-0">
      <%= render 'table' %>
    </div>
</div>
<%= paginate @jobs, theme: 'twitter-bootstrap-4' %>

app/views/jobs/show.html.erb
<% if @job.name %>
    <% content_for(:tabtitle, "Job: #{@job.name.truncate(15, omission: "...#{@job.name.last(7)}")} - Valve Dashboard") %>
<% end %>
<% content_for :title do %>
    <% if @job.is_released_code %>
        <span class="badge badge-success" style="color: white;">Post-merge</span>
    <% else %>
        <span class="badge badge-warning" style="color: white;">Pre-merge</span>
    <% end %>
    Overview of the <%= @job.name %> job
<% end %>
<%= render 'pre_merge' %>

app/views/jobs/show.js.erb
$("#failures").html("<%= j render partial: 'regressions', locals: {bool: false} %>")
$("#executions").html("<%= j render 'executions' %>")