config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :games
  resources :benches, :path => "benchmarks" do
    collection do
      match 'stats' => 'benches#stats', via: [:get, :post], as: :stats
    end
  end
  resources :runs
  resources :traces do
    collection do
      match 'line_chart_amount' => 'traces#line_chart_amount', via: [:get], as: :line_chart_amount
    end
    member do
      get 'execution_time'
      get 'frames/:frame_id', to: 'traces#frames'
      post 'frames/:frame_id', to: 'traces#frames'
    end
    resources :trace_frames do
      resources :frame_outputs
    end
  end
  resources :static, only: [:index] do
    collection do
      get 'get_url'
      get 'get_ref_frames'
      post 'get_ref_frames'
    end
  end
  resources :users, only: [:edit, :show, :update, :index] do
    member do
      get 'edit_permissions'
    end
  end
  resources :gpus do
    member do
      get 'gpu_frames'
      get 'execution_time'
    end
    resources :frame_outputs
  end
  resources :frame_outputs do
    member do
      get 'history', to: 'frame_outputs#history'
    end
  end
  resources :games_tags, only: [:destroy]
  resources :bugs, only: [:create, :destroy, :index, :show, :update, :new] do
    member do
      post 'associate'
      post 'mark_fixed'
      post 're_open'
      get 'create_upstream_issue'
    end
    collection do
      match 'line_chart_amount' => 'bugs#line_chart_amount', via: [:get], as: :line_chart_amount
    end
  end
  resources :bugs_trace_frames, only: [:destroy]
  resources :jobs, only: [:destroy, :index, :show]
  resources :deduped_frame_outputs do
    member do
      post 'acceptable_frame'
      post 'unacceptable_frame'
      get 'frame_bug'
      get 'pre_merge_frame_bug'
      get 'issue'
      get 'next_frame'
      post 'dissociate'
    end
  end
  match 'stats' => 'static#stats', via: [:get], as: :stats
  resources :trace_execs
  resources :providers, only: [:destroy]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :graphics_apis
      match 'checksum' => 'static#checksum', via: [:get, :post], as: :checksum
      match 'image_checksum' => 'static#image_checksum', via: [:get, :post], as: :image_checksum
      match 'unoptimized_traces' => 'static#unoptimized_traces', via: [:get, :post], as: :unoptimized_traces
      match 'trace_lock' => 'static#trace_lock', via: [:get, :post], as: :trace_lock
      match 'frames_needing_review' => 'static#frames', via: [:get], as: :frames
      devise_scope :user do
        post 'login', to: 'sessions#create'
      end
      resources :traces do
        collection do
          match 'enrollment' => 'traces#enrollment', via: [:get], as: :enrollment
        end
      end
      resources :games
      resources :runs
      resources :jobs do
        resources :trace_execs
      end
      resources :trace_execs
      resources :gpus
      resources :users, only: [:index]
      resources :trace_compatibilities
      resources :commits
      resources :projects
      resources :benches
      resources :stats do
        collection do
          match 'frame_outputs' => 'stats#frame_outputs', via: [:get, :post], as: :frame_outputs
          get 'trace_frames/:id/' => 'stats#trace_frames', via: [:get], as: :trace_frames
          get 'blobs/:id/' => 'stats#blobs', via: [:get], as: :blobs
        end
      end
      resources :deduped_frame_outputs
    end
  end
  match "/-/profile", to: "users#profile", via: [:get], as: :profile
  match 'frames_needing_review' => 'static#frames', via: [:get], as: :frames
  match 'gpu_frames' => 'static#gpu_frames', via: [:get, :post], as: :gpu_frames
  root 'static#index'
end

app/models/game.rb
class Game < ApplicationRecord
    has_many :runs
    has_many :traces, dependent: :destroy
    has_many :benches, through: :runs
    has_and_belongs_to_many :tags
    validates :appid, uniqueness: true, if: Proc.new { |game| game.appid.present? }
    validates :name, uniqueness: true

    # def self.steam_game_query(trace, appid)
    #     require 'net/http'
    #     source = "https://store.steampowered.com/api/appdetails?appids=" + appid
    #     resp = Net::HTTP.get_response(URI.parse(source))
    #     json = JSON.parse(resp.body)
    #     if json[appid]["success"]
    #         @game = Game.create!(name: json[appid]["data"]["name"], appid: appid)
    #         trace.game = @game
    #         return trace
    #     else
    #         render html: "Incorrect appid: #{appid}"
    #         return nil
    #     end
    # end

    # def self.steam_get_name(appid)
    #     require 'net/http'
    #     appid = appid.to_s
    #     source = "https://store.steampowered.com/api/appdetails?appids=" + appid
    #     resp = Net::HTTP.get_response(URI.parse(source))
    #     json = JSON.parse(resp.body)
    #     if json[appid]["success"]
    #         return json[appid]["data"]["name"]
    #     else
    #         return false
    #     end
    # end
end

app/controllers/api/v1/games_controller.rb
module Api
    module V1
        class GamesController < ApplicationController
            skip_forgery_protection
            before_action :can_create_game, only: [:create]
            before_action :admin, except: [:create, :index]
            before_action :authenticate_user!, except: [:index]

            def index
                @games = Game.all.includes(:traces)
            end

            def create
                @game = Game.new(game_params)
                @game = Game.create(game_params)
                if @game.errors.any?
                    render json: @game.errors
                else
                    render json: @game
                end
            end

            private
            def game_params
                params.require(:game).permit(:name, :appid)
            end

        end
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    before_action :can_create_game, only: [:create, :new], except: [:show, :index]
    before_action :can_destroy_game, only: [:destroy], except: [:show, :index, :new]
    before_action :can_edit_game, only: [:edit, :update], except: [:show, :index, :new]
    before_action :authenticate_user!, except: [:show, :index]
    before_action :admin, except: [:show, :index, :destroy, :create, :edit, :update, :new]

    def index
        @q = Game.ransack(params[:q])
        @games = @q.result(distinct: true)
        @tags = Tag.order(name: :asc).uniq
    end

    def new
        @game = Game.new
    end

    def create
        @game = Game.new(game_params)
        respond_to do |format|
            if @game.save
                if params[:add_tag] != ""
                    @tag = Tag.find_or_create_by(name: params[:add_tag])
                    GamesTag.create(game_id: @game.id, tag_id: @tag.id) unless GamesTag.where(game_id: @game.id, tag_id: @tag.id).any?
                end
                format.html { redirect_to @game, notice: 'game was successfully created.' }
                format.json { render :edit, status: :created, location: @game }
                format.js
            else
                format.html {render json: @game.errors}
            end
        end
    end
    
    def edit
        @game = Game.find(params[:id])
    end
    
    def show
        @game = Game.find(params[:id])
        @trace = Trace.new
        @trace.trace_frames.build
        @traces = @game.traces.where(deleted: [nil, false])
        @gpu = Gpu.new
    end

    def update
        @game = Game.find(params[:id])
        if params[:add_tag] != ""
            @tag = Tag.find_or_create_by(name: params[:add_tag])
            GamesTag.create(game_id: @game.id, tag_id: @tag.id) unless GamesTag.where(game_id: @game.id, tag_id: @tag.id).any?
        end
        redirect_to game_path(@game)
    end

    def destroy
        @game = Game.find(params[:id])
        @game.destroy
        redirect_to games_path
    end

    private
    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :appid, :trace_status, tags: [], :traces => [])
    end
end

app/views/games/_bench_table.html.erb
<div class="row">
  <div class="col-sm-12">
    <table class="table table-bordered">
      <thead>
        <th>#</th>
        <th>Benchmark</th>
        <th>Avg FPS</th>
      </thead>
      <tbody>
        <% @game.benches.each do |benchmark| %>
        <tr>
            <td><%= benchmark.id %></td>
            <td><%= link_to benchmark.name, benchmark %></td>
            <td><%= benchmark.metrics.where(label: "fps").first.avg.round(2) if benchmark.metrics.where(label: "fps").any? %>
            <% if params[:action] == "index" %>
                <td>
                    <%= link_to "Edit", edit_bench_path(benchmark), class: "btn btn-sm btn-warning" %>
                    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        bench_path(benchmark),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-sm btn-danger', remote: false %>
                </td>
            <% else %>
                <td><%= (((benchmark.metrics.where(label: "fps").first.avg.round(2) / @game.benches.first.metrics.where(label: "fps").first.avg.round(2)) * 100).round(2)).to_s + "%" if benchmark.metrics.where(label: "fps").any? %></td>
            <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                <%= f.label :name, :class => 'control-label' %>
                <div class="controls">
                    <%= f.text_field :name, required: true, :class => 'form-control' %>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <%= f.label :status, :class => 'control-label' %>
                <div class="controls">
                    <%= f.collection_select :trace_status, Trace::TRACE_STATUS, :to_s, :to_s, {}, required: true, class: 'form-control' %>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <%= f.label :Add_tag, :class => 'control-label' %>
                <div class="controls">
                    <%= text_field_tag('add_tag', nil, list: 'tag-list', :autocomplete => :off)  %>
                    <datalist id="tag-list">
                        <% Tag.all.select(:name).distinct.each do |tag| %>
                            <option value="<%= tag.name %>"></option>
                        <% end %>
                    </datalist>
                </div>
            </div>
        </div>
    </div>
<%= f.submit class: "btn btn-success" %>
<% end %>

app/views/games/_table.html.erb
<div class="row">
  <div class="col-sm-12">
    <table class="table table-bordered">
      <thead>
        <th><%= sort_link(@q, :name) do %>
              <strong>Game</strong>
            <% end %>
        </th>
        <th>Traces</th>
        <th><%= sort_link(@q, :trace_status) do %>
              <strong>Status</strong>
            <% end %>
        </th>
        <th>Tags</th>
        <% if current_user && (current_user.can_edit_game? || current_user.can_destroy_game?) %>
          <th>Tools</th>
        <% end %>
      </thead>
      <tbody>
        <% @games.joins(:tags).includes(:traces).order(:name).each do |game| %>
        <tr>
            <td><%= link_to game.name, game %>
            <td><%= game.traces.where(deleted: [nil, false]).size %></td>
            <td><%= game.trace_status %></td>
            <td>
              <% game_tags = game.tags.order(name: :asc) %>
              <% game_tags.each do |tag| %>
                <%= tag.name %><%= "," if tag != game_tags.last %>
              <% end %>
            </td>
            <% if current_user && (current_user.can_edit_game? || current_user.can_destroy_game?) %>
              <td>
                <%= link_to "Edit", edit_game_path(game), class: "btn btn-sm btn-warning" if current_user.can_edit_game? %>
                <%= link_to "Destroy", game_path(game), method: :delete, class: "btn btn-sm btn-danger", data: {confirm: "Are you sure?"} if current_user.can_destroy_game? %>
              </td>
            <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/games/_trace_table.html.erb
<div class="row">
  <div class="col-sm-12">
    <table class="table table-bordered">
      <thead>
        <th>#</th>
        <th>Trace</th>
        <th>GPU</th>
        <th>Size</th>
        <% if current_user && current_user.can_upload_trace? %>
          <th>Tools</th>
        <% end %>
      </thead>
      <tbody>
        <% @traces.order(:id).each do |trace| %>
        <tr>
            <td><%= link_to trace.id, trace %></td>
            <td><%= link_to trace.upload.filename.to_s.truncate(20), trace.upload, :"data-turbolinks" => false if trace.upload.attached? %></td>
            <td><%= trace.gpu.name if trace.gpu %></td>
            <td><%= number_to_human_size(trace.upload.blob.byte_size) if trace.upload.attached? %></td>
            <% if current_user && current_user.can_upload_trace? %>
            <td>
              <%= link_to "Destroy",
                  trace_path(trace),
                  :method => :delete,
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-sm btn-danger', remote: false %>
            </td>
            <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/games/_upload.html.erb
<div class="row">
    <div class="col-12">
        <%= form_for @game, remote: true do |f| %>
            <div class="row">
                <div class="col-12">
                    <%= f.file_field :traces, multiple: true, direct_upload: true, class: "" %>
                </div>
            </div></p>
            <div class="row">
                <div class="col-2">
                    <%= f.submit "Upload", class: 'btn btn-success' %>
                </div>
                <div class="row">
                <div class="col-12">
                <table class="table table-bordered" id="upload-table">
                    <tbody id="upload-tbody">
                        <tr>
                            <td id="num_uploads">0</td>
                            <td id="mbps">0 mb/s</td>
                        </tr>
                    </tbody>
                </table>

                </div>
                </div>
            </div>

        <% end %>
    </div>
</div>

app/views/games/edit.html.erb
<%= render 'form' %>

app/views/games/index.html.erb
<% content_for(:tabtitle, "Games - Valve Dashboard") %>
<% content_for :title do %> Games <% end %>
<div class="row">
  <div class="col-8">
    <div class="card">
      <div class="card-body p-3">
        <%= search_form_for @q do |f| %>
          <div class="row">
            <div class="col">
              <%= f.label "Game name" %>
              <%= f.search_field :name_cont, class: "form-control" %></p>
              <%= link_to "New Game", new_game_path, class: "btn btn-primary" if current_user && current_user.can_create_game? %>
              <%= f.submit %>
              </p>
            </div>
            <div class="col">
              <%= f.label "Tags" %>
              <%= f.collection_select(:tags_id_in, @tags.uniq, :id, :name, {include_blank: true}, {multiple: true, class: "form-control"}) %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
    <div class="col-4">
    <%= pie_chart Game.group(:trace_status).count %>
  </div>
</div>

</p>
<div class="card">
    <div class="card-header">
        <h3 class="card-title">Games</h3>
        <div class="card-tools">
        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body p-0 mb-n3">
      <%= render 'table' %>
    </div>
</div>

app/views/games/new.html.erb
<% content_for :title do %> New Game <% end %>
<%= render 'form' %>

app/views/games/show.html.erb
<% content_for(:tabtitle, "Game: #{@game.name} - Valve Dashboard") %>
<% content_for :title do %> <%= @game.name %> <% end %>
<%= link_to "Edit", edit_game_path(@game), class: "btn btn-warning" %></p>
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-header">
                <h4>Tags</h4>
            </div>
            <div id="layer_list" class="list-group">
                <% @game.tags.each do |tag| %>
                    <div id="list_<%= tag.id %>" class="list-group-item">
                        <div class="row">
                            <div class="col-10">
                                &nbsp;<%= tag.name %>
                            </div>
                            <% if current_user && current_user.can_edit_game? %>
                                <div class="col-2">
                                    <%= link_to games_tag_path(tag_id: tag.id, game_id: @game.id), method: :delete do %>
                                        <i style="color: red;" class="fas fa-minus-circle pull-right"></i>
                                    <% end %>
                                </div>
                            <% end %>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
    <% if current_user && current_user.can_upload_trace? %>
    <div class="col">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">New GPU</h3>
                <div class="card-tools">
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body p-3">
                <%= render 'gpus/form' %>
            </div>
        </div>
    </div>
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">New Trace</h3>
                    <div class="card-tools">
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body p-3">
                    <%= render 'traces/form' %>
                </div>
            </div>
        </div>
    <% end %>
</div>


<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Traces</h3>
                <div class="card-tools">
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body p-0 mb-n3">
                    <%= render 'trace_table' %>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Benchmarks</h3>
                <div class="card-tools">
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body p-0 mb-n3">
                    <%= render partial: 'benches/table', locals: {benchmarks: @game.benches.uniq} %>
            </div>
        </div>
    </div>
</div>
<script>
var trace_frame_count = 1
</script>

app/views/games/show.js.erb
<% count = params[:trace_frame_count] %>
'<%= form_for @trace, remote: true do |f| %>'
    $('#trace_frames tbody').append("<%= j render partial: 'traces/form_trace_frames', locals: {f: f, count: count} %>")
'<% end %>'
trace_frame_count++;