config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :games
  resources :benches, :path => "benchmarks" do
    collection do
      match 'stats' => 'benches#stats', via: [:get, :post], as: :stats
    end
  end
  resources :runs
  resources :traces do
    collection do
      match 'line_chart_amount' => 'traces#line_chart_amount', via: [:get], as: :line_chart_amount
    end
    member do
      get 'execution_time'
      get 'frames/:frame_id', to: 'traces#frames'
      post 'frames/:frame_id', to: 'traces#frames'
    end
    resources :trace_frames do
      resources :frame_outputs
    end
  end
  resources :static, only: [:index] do
    collection do
      get 'get_url'
      get 'get_ref_frames'
      post 'get_ref_frames'
    end
  end
  resources :users, only: [:edit, :show, :update, :index] do
    member do
      get 'edit_permissions'
    end
  end
  resources :gpus do
    member do
      get 'gpu_frames'
      get 'execution_time'
    end
    resources :frame_outputs
  end
  resources :frame_outputs do
    member do
      get 'history', to: 'frame_outputs#history'
    end
  end
  resources :games_tags, only: [:destroy]
  resources :bugs, only: [:create, :destroy, :index, :show, :update, :new] do
    member do
      post 'associate'
      post 'mark_fixed'
      post 're_open'
      get 'create_upstream_issue'
    end
    collection do
      match 'line_chart_amount' => 'bugs#line_chart_amount', via: [:get], as: :line_chart_amount
    end
  end
  resources :bugs_trace_frames, only: [:destroy]
  resources :jobs, only: [:destroy, :index, :show]
  resources :deduped_frame_outputs do
    member do
      post 'acceptable_frame'
      post 'unacceptable_frame'
      get 'frame_bug'
      get 'pre_merge_frame_bug'
      get 'issue'
      get 'next_frame'
      post 'dissociate'
    end
  end
  match 'stats' => 'static#stats', via: [:get], as: :stats
  resources :trace_execs
  resources :providers, only: [:destroy]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :graphics_apis
      match 'checksum' => 'static#checksum', via: [:get, :post], as: :checksum
      match 'image_checksum' => 'static#image_checksum', via: [:get, :post], as: :image_checksum
      match 'unoptimized_traces' => 'static#unoptimized_traces', via: [:get, :post], as: :unoptimized_traces
      match 'trace_lock' => 'static#trace_lock', via: [:get, :post], as: :trace_lock
      match 'frames_needing_review' => 'static#frames', via: [:get], as: :frames
      devise_scope :user do
        post 'login', to: 'sessions#create'
      end
      resources :traces do
        collection do
          match 'enrollment' => 'traces#enrollment', via: [:get], as: :enrollment
        end
      end
      resources :games
      resources :runs
      resources :jobs do
        resources :trace_execs
      end
      resources :trace_execs
      resources :gpus
      resources :users, only: [:index]
      resources :trace_compatibilities
      resources :commits
      resources :projects
      resources :benches
      resources :stats do
        collection do
          match 'frame_outputs' => 'stats#frame_outputs', via: [:get, :post], as: :frame_outputs
          get 'trace_frames/:id/' => 'stats#trace_frames', via: [:get], as: :trace_frames
          get 'blobs/:id/' => 'stats#blobs', via: [:get], as: :blobs
        end
      end
      resources :deduped_frame_outputs
    end
  end
  match "/-/profile", to: "users#profile", via: [:get], as: :profile
  match 'frames_needing_review' => 'static#frames', via: [:get], as: :frames
  match 'gpu_frames' => 'static#gpu_frames', via: [:get, :post], as: :gpu_frames
  root 'static#index'
end

app/models/bench.rb
class Bench < ApplicationRecord

    has_many :runs, dependent: :destroy
    has_many :sysinfos, dependent: :destroy
    has_many :games, through: :runs
    
    TWENTY    =  [ '#e6194b', '#3cb44b', '#4363d8', '#911eb4', '#f58231', '#E899DC', '#bcf60c', '#fabebe', '#008080', '#e6beff', '#9a6324', '#fffac8',
        '#800000', '#aaffc3', '#808000', '#000075', '#808080' ]
    SYNC = ["NONE", "ESYNC", "FSYNC", "FUTEX2"]
    FILETYPES = ["MANGO", "HML"]
end

app/controllers/api/v1/benches_controller.rb
module Api
    module V1
        class BenchesController < ApplicationController
            skip_forgery_protection

            def index
                @q = Bench.ransack(params[:q])
                @benchmarks = @q.result
                respond_to do |f|
                    f.json
                end
            end

            def new
                @benchmark = Bench.new
            end

            def create
                @benchmark = Bench.new(bench_params)
                if @benchmark.save
                    render json: @benchmark
                end
            end
            
            def edit
                @benchmark = Bench.find(params[:id])
            end
            
            def show
                @benchmark = Bench.find(params[:id])
                @run = Run.new
            end

            def update
                @benchmark = Bench.find(params[:id])
                if @benchmark.update(bench_params)
                    redirect_to bench_path(@benchmark), flash: {success: 'Successfully updated benchmark'}
                end
            end

            def destroy
                @benchmark = Bench.find(params[:id])
                @benchmark.destroy
                redirect_to root_path
            end

            private
            # Never trust parameters from the scary internet, only allow the white list through.
            def bench_params
            params.require(:bench).permit(:name, :type_name)
            end
        end
    end
end

app/controllers/benches_controller.rb
class BenchesController < ApplicationController
    def index
        @q = Bench.ransack(params[:q])
        @benchmarks = @q.result
    end

    def new
        @benchmark = Bench.new
    end

    def create
        @benchmark = Bench.new(bench_params)
        respond_to do |format|
            format.html { redirect_to @benchmark, notice: 'Benchmark was successfully created.' }
            format.json { render :edit, status: :created, location: @benchmark }
            format.js
        end
    end
    
    def edit
        @benchmark = Bench.find(params[:id])
    end
    
    def show
        @benchmark = Bench.find(params[:id])
        @run = Run.new
    end

    def update
        @benchmark = Bench.find(params[:id])
        if @benchmark.update(bench_params)
            respond_to do |format|
                format.html { redirect_to bench_path(@benchmark), flash: {success: 'Successfully updated benchmark'} }
            end
        end
    end

    def destroy
        @benchmark = Bench.find(params[:id])
        @benchmark.destroy
        redirect_to root_path
    end

    private
    # Never trust parameters from the scary internet, only allow the white list through.
    def bench_params
      params.require(:bench).permit(:name, :type_name)
    end
end

app/helpers/benches_helper.rb
module BenchesHelper
end

app/views/benches/_checkboxes.html.erb
<script>
$('input[type=checkbox]').each(function () {
  $(this).prop("checked", false);
})
bench_ids=[]
function checkBoxBenchmark(id){
found = false;
for (let i = 0; i < bench_ids.length; i++) {
  if (bench_ids[i] == id){
    bench_ids.splice(i, 1);
    found = true;
  }
}
if (!found)
  bench_ids.push(id)
}

function displayMarked(){
  Turbolinks.visit("/benchmarks/stats?bench_ids=" + "[" + bench_ids + "]")
}
</script>

app/views/benches/_compare_graphs.html.erb
<% colors = Bench::TWENTY %>
<div class="row">
    <div class="col-6">
        <%= column_chart benchmarks.average("inputs.fps"),
            title: "Average FPS", colors: colors, max: 100, library: { plotOptions: { column: { colorByPoint: true }}} %>
    </div>
    <div class="col-6">
        <%= column_chart benchmarks.average("inputs.gpu_power"),
            title: "GPU Power Consumption", colors: colors, max: 100, library: { plotOptions: { column: { colorByPoint: true }}} %>
    </div>
</div></p>
<div class="row">
    <div class="col-6">
        <%= column_chart benchmarks.average("inputs.gpu"),
            title: "GPU Load", colors: colors, max: 100, library: { plotOptions: { column: { colorByPoint: true }}} %>
    </div>
    <div class="col-6">
        <%= column_chart benchmarks.average("inputs.cpu"),
            title: "CPU Load", colors: colors, max: 100, library: { plotOptions: { column: { colorByPoint: true }}} %>
    </div>
</div></p>

app/views/benches/_compare_table.html.erb
<div class="row">
  <div class="col-sm-12">
    <table class="table table-bordered">
      <thead>
        <% if type == "Wine" %>
            <th>Proton/Wine</th>
        <% end %>
        <% if type == "Renderer" %>
            <th>Renderer</th>
        <% end %>
        <th>Avg FPS</th>
        <th>Compared to <%= benchmarks.first if benchmarks.any? %></th>
      </thead>
      <tbody>
        <% benchmarks.each do |benchmark| %>
        <tr>
            <td><%= benchmark %>
            <% if type == "Wine" %>
                <td><%= @benchmarks.where(wine: benchmark).joins(:inputs).average("inputs.fps").round(2) if @benchmarks.where(wine: benchmark).first.inputs.any? %>
            <% end %>
            <% if type == "Renderer" %>
                <td><%= @benchmarks.where(renderer: benchmark).joins(:inputs).average("inputs.fps").round(2) if @benchmarks.where(renderer: benchmark).first.inputs.any? %>
            <% end %>
            <% if type == "Wine" %>
                <td><%= (@benchmarks.where(wine: benchmark).joins(:inputs).average("inputs.fps") / @benchmarks.where(wine: benchmarks.first).joins(:inputs).average("inputs.fps") * 100).round(2).to_s + "%" if @benchmarks.where(wine: benchmark).first.inputs.any? %></td>
            <% end %>
            <% if type == "Renderer" %>
                <td><%= (@benchmarks.where(renderer: benchmark).joins(:inputs).average("inputs.fps") / @benchmarks.where(renderer: benchmarks.first).joins(:inputs).average("inputs.fps") * 100).round(2).to_s + "%" if @benchmarks.where(renderer: benchmark).first.inputs.any? %></td>
            <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/benches/_form.html.erb
<%= form_for @benchmark do |f| %>
    <div class="row">
        <div class="col-sm-4">
            <div class="form-group">
                <%= f.label :name, :class => 'control-label' %>
                <div class="controls">
                    <%= f.text_field :name, :class => 'form-control' %>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="form-group">
                <%= f.label :type, :class => 'control-label' %>
                <div class="controls">
                    <%= f.text_field :type_name, list: 'type-list', class: "form-control", :autocomplete => :off %>
                    <datalist id="type-list">
                        <% Bench.all.select(:type_name).distinct.each do |bench| %>
                            <option value="<%= bench.type_name %>"></option>
                        <% end %>
                    </datalist>
                </div>
            </div>
        </div>
        <div class="col-sm-2">
            <div class="form-group">
                <label class="control-label" for="bench_type">&nbsp;</label>
                <div class="controls">
                    <%= f.submit nil, :class => 'btn btn-primary' %>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/benches/_graphs.html.erb
<% runs = game.runs.where(bench: benchmark) %>
<% colors = Bench::TWENTY %>
<div class="card">
    <div class="card-body p-0">
      <%= render partial: 'stats_table', locals: {benchmark: benchmark, runs: runs, colors: colors} %>
    </div>
</div>

<% if params[:action] != "sync" || params[:q].nil? %>
<div class="row">
    <div class="col-6">
        <%= line_chart runs.map {|run| {name: run.name, data: run.metrics.select(:data, :label).where(label: "elapsed").first.data.zip(run.metrics.where(label: "fps").first.data)}},
            title: "FPS", colors: colors, round: 0, suffix: "FPS" %>
    </div>
    <div class="col-6">
        <%= line_chart runs.map {|run| {name: run.name, data: run.metrics.select(:data, :label).where(label: "elapsed").first.data.zip(run.metrics.where(label: "frametime").first.data)}},
            title: "Frametime", colors: colors, round: 0, suffix: "ms" %>
    </div>
</div></p>
<% end %>
<div class="row">
    <div class="col-6">
        <%= column_chart runs.map {|run| {name: run.name, data: [["Average GPU Load", run.metrics.select(:avg).where(label: "gpu_load").first.avg]]}},
            title: "GPU Load", colors: colors, max: 100, library: { plotOptions: { column: { colorByPoint: false }}}, suffix: "%" %>
    </div>
    <div class="col-6">
        <%= column_chart runs.map {|run| {name: run.name, data: [["Average GPU Load", run.metrics.select(:avg).where(label: "cpu_load").first.avg]]}},
            title: "CPU Load", colors: colors, max: 100, library: { plotOptions: { column: { colorByPoint: false }}}, suffix: "%" %>
    </div>
</div></p>
<div class="row">
    <div class="col-6">
        <%= column_chart runs.map {|bench| {name: bench.game.name + " " + bench.name, data: [["Average GPU Watt", bench.metrics.select(:avg).where(label: "gpu_power").first.avg]]}},
            title: "GPU Watt", colors: colors, library: { plotOptions: { column: { colorByPoint: false }}}, suffix: "W" %>
    </div>
    <% if @benchmark.runs.any? %>
        <% if @benchmark.runs.last.metrics.pluck(:label).include? "current_watt" %>
            <%# if Run.last.metrics.find_by(label: "current_watt").avg > 0 %>
            <div class="col-6">
                <%#= column_chart runs.map {|bench| {name: bench.game.name + " " + bench.name, data: [["Average Energy Rate", bench.metrics.select(:avg).where(label: "current_watt").first.avg]]}},
                    title: "Energy Rate", colors: colors, library: { plotOptions: { column: { colorByPoint: false }}}, suffix: "W" %>
            </div>
            <%# end %>
        <% end %>
    <% end %>
</div></p>
<div class="row">
    <div class="col-6">
        <%#= line_chart benchmarks.map { |bench| 
            {name: bench.name, data: bench.inputs.where(id: bench.inputs.map {|input| input if input.id % 10 == 0 }).group(:position).sum(:gpu_core_clock)}}, title: "GPU Core Clock", colors: colors %>
    </div>
    <div class="col-6">
        <%#= line_chart benchmarks.map { |bench| 
            {name: bench.name, data: bench.inputs.where(id: bench.inputs.map {|input| input if input.id % 10 == 0 }).group(:position).sum(:gpu_power)}}, title: "GPU Power Consumption", ytitle: "Watt", colors: colors %>
    </div>
</div></p>
<div class="row">
    <div class="col-6">
        <%#= column_chart benchmarks.group(:sync).joins(:inputs).average("inputs.fps"), title: "Sync Compare", colors: colors, library: { plotOptions: { column: { colorByPoint: true }}} %>
    </div>
    <div class="col-6">
        <%#= column_chart benchmarks.group(:driver).joins(:inputs).average("inputs.fps"), title: "Driver Compare", colors: colors, library: { plotOptions: { column: { colorByPoint: true }}} %>
    </div>
</div>

app/views/benches/_graphs_total.html.erb
<% colors = Bench::TWENTY %>
<% types = benchmark.runs.pluck(:name).uniq %>
<div class="card">
    <div class="card-body p-0">
      <%= render partial: 'stats_table_total', locals: {benchmark: benchmark, types: types, colors: colors} %>
    </div>
</div>

<% if params[:action] != "sync" || params[:q].nil? %>
<div class="row">
    <div class="col-6">
        <%= bar_chart types.map { |type| {name: type, data: [["FPS", benchmark.runs.where(name: type).includes(:metrics).select(metrics: [:label, :avg]).where(metrics: {label: "fps"}).average(:avg)]] }},
            title: "FPS", colors: colors, library: { plotOptions: { column: { colorByPoint: false }}}, suffix: "fps" %>
    </div>
    <div class="col-6">
        <%= bar_chart types.map { |type| {name: type, data: [["Frametime", benchmark.runs.where(name: type).includes(:metrics).select(metrics: [:label, :avg]).where(metrics: {label: "frametime"}).average(:avg)]] }},
            title: "Frametime", colors: colors, library: { plotOptions: { column: { colorByPoint: false }}}, suffix: "ms" %>
    </div>
</div></p>
<% end %>
<div class="row">
    <div class="col-6">
        <%= column_chart types.map { |type| {name: type, data: [["Average GPU Load", benchmark.runs.where(name: type).includes(:metrics).select(metrics: [:label, :avg]).where(metrics: {label: "gpu_load"}).average(:avg)]] }},
            title: "GPU Load", colors: colors, max: 100, library: { plotOptions: { column: { colorByPoint: false }}}, suffix: "%" %>
    </div>
    <div class="col-6">
        <%= column_chart types.map { |type| {name: type, data: [["Average CPU Load", benchmark.runs.where(name: type).includes(:metrics).select(metrics: [:label, :avg]).where(metrics: {label: "cpu_load"}).average(:avg)]] }},
            title: "CPU Load", colors: colors, max: 100, library: { plotOptions: { column: { colorByPoint: false }}}, suffix: "%" %>
    </div>
</div></p>

<div class="row">
    <div class="col-6">
        <%= column_chart types.map { |type| {name: type, data: [["Average GPU Watt", benchmark.runs.where(name: type).includes(:metrics).select(metrics: [:label, :avg]).where(metrics: {label: "gpu_power"}).average(:avg)]] }},
            title: "GPU Watt", colors: colors, max: 100, library: { plotOptions: { column: { colorByPoint: false }}}, suffix: "W" %>
    </div>
    <% if @benchmark.runs.any? %>
        <% if @benchmark.runs.last.metrics.pluck(:label).include? "current_watt" %>
            <%# if Run.last.metrics.find_by(label: "current_watt").avg > 0 %>
            <div class="col-6">
                <%#= column_chart types.map { |type| {name: type, data: [["Average Energy Rate", benchmark.runs.where(name: type).includes(:metrics).select(metrics: [:label, :avg]).where(metrics: {label: "current_watt"}).average(:avg)]] }},
                    title: "Energy rate", colors: colors, max: 100, library: { plotOptions: { column: { colorByPoint: false }}}, suffix: "W" %>
            </div>
            <%# end %>
        <% end %>
    <% end %>
</div></p>

app/views/benches/_stats_table.html.erb
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Color</th>
            <th>Name</th>
            <th>Avg</th>
            <th>Avg % vs <%= runs.first.name %></th>
            <% if current_user.admin? %>
                <th>Tools</th>
            <% end %>
            <th>System</th>
        </tr>
    </thead>
    <tbody>
        <% runs.each_with_index do |run, i| %>
            <tr>
                <td style="background-color: <%= colors[i] %>; width: 5%;"></td>
                <td><%= run.name %></td>
                <td><%= @avg = run.metrics.select(:label, :avg).where(label: "fps").last.avg.round(1) %></td>
                <td><%= (((@avg / runs.first.metrics.select(:label, :id, :avg).where(label: "fps").first.avg.round(1) * 100).round(1))).to_s + "%" if runs.first.metrics.where(label: "fps").where.not(data: nil) %></td>
                <% if current_user.admin? %>
                    <td>
                        <%= link_to "Destroy",
                        run_path(run),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-sm btn-danger', remote: false %>
                    </td>
                <% end %>
                <td>
                    <% if run.sysinfos.any? %>
                        <% if run.sysinfos.select(:label, :info).where(label: "Wine/Proton").last.info == nil %>
                            Windows
                        <% else %>
                            <%= run.sysinfos.select(:label, :info).where(label: "Wine/Proton").last.info %>
                        <% end %>
                    <% end %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/benches/_table.html.erb
<div class="row">
  <div class="col-sm-12">
    <table class="table table-bordered">
      <thead>
        <th style="width: 1px;">#</th>
        <th>Benchmark</th>
      </thead>
      <tbody>
        <% benchmarks.each do |benchmark| %>
        <tr>
            <td style="width: 1px;"><%= benchmark.id %></td>
            <td><%= link_to benchmark.name, benchmark %></td>
            <!--
            <td><%#= benchmark.games.size %></td>
            <td>
                <%#= link_to "Edit", edit_bench_path(benchmark), class: "btn btn-sm btn-warning" %>
                <%#= link_to "Destroy",
                    bench_path(benchmark),
                    :method => :delete,
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                    :class => 'btn btn-sm btn-danger', remote: false %>
            </td>
            -->
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<div class="row">
<!--  <div class="col-3 ml-1">
    <button class="btn btn-primary" onclick="displayMarked();">Show marked Benchmarks</button></p>
  </div> -->
  <div class="col-8">
    <%#= link_to 'Compare by Native', stats_benches_path(benchmark_ids: @benchmarks.pluck(:id), type: "Wine"), remote: true , class: "btn btn-success" %>
    <%#= link_to 'Compare by Renderer', stats_benches_path(benchmark_ids: @benchmarks.pluck(:id), type: "Renderer"), remote: true , class: "btn btn-success" %>
  </div>
</div>

app/views/benches/edit.html.erb
<%= render 'form' %>

app/views/benches/index.html.erb
<% content_for :title do %> Benchmarks <% end %>
<%= link_to "New Benchmark", new_bench_path, class: "btn btn-primary" if current_user.admin? %>
</p>
<div class="card">
    <div class="card-header">
        <h3 class="card-title">Benchmarks</h3>
        <div class="card-tools">
        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body p-0">
        <%= render partial: 'table', locals: {benchmarks: @benchmarks} %>
        <%= render 'checkboxes' %>
    </div>
</div>

app/views/benches/new.html.erb
<% content_for :title do %> New Benchmark <% end %>
<%= render 'form' %>

app/views/benches/show.js.erb
<% if params[:game_id] == "total" %>
$('#stats_table').html("<%= j render partial: 'graphs_total', locals: {benchmark: @benchmark, game: @benchmark.games.first} %>")
<% else %>
$('#stats_table').html("<%= j render partial: 'graphs', locals: {benchmark: @benchmark, game: @benchmark.games.find(params[:game_id])} %>")
<% end %>

app/views/benches/stats.html.erb
<% content_for :title do %> Benchmark stats <% end %>
<div class="card">
    <div class="card-header">
        <%= search_form_for @q, url: stats_benches_path,
                                html: { method: :post } do |f| %>
        <div class="row">
            <div class="col-3">
                <%= f.label "Renderer" %>
                <%= f.collection_select :renderer_cont, Bench.select(:renderer).distinct.where.not(renderer: nil), :renderer, :renderer, {include_blank: true}, class: 'form-control', placeholder: "Type" %>
            </div>
            <div class="col-3">
                <%= f.label "Game" %>
                <%= f.collection_select :game_id_eq, Game.all, :id, :name, {include_blank: true}, class: 'form-control' %>
            </div>
            <div class="col-3">
                <%= f.label "Sync" %>
                <%= f.collection_select :sync_cont, Bench.select(:sync).distinct.where.not(sync: nil), :sync, :sync, {include_blank: true}, class: 'form-control' %>
            </div>
            <div class="col-3">
                <%= f.label "Driver" %>
                <%= f.collection_select :driver_cont, Bench.select(:driver).distinct, :driver, :driver, {include_blank: true}, class: 'form-control' %>
            </div>
            <div class="col-3">
                <%= f.label "Cpu Scheduler" %>
                <%= f.collection_select :cpusched_cont, Bench.select(:cpusched).distinct, :cpusched, :cpusched, {include_blank: true}, class: 'form-control' %>
            </div>
            <div class="col-3">
                <%= f.label "Kernel" %>
                <%= f.collection_select :kernel_cont, Bench.select(:kernel).distinct.where.not(kernel: nil), :kernel, :kernel, {include_blank: true}, class: 'form-control' %>
            </div>
            <div class="col-3">
                <%= f.label "Proton/Wine" %>
                <%= f.collection_select :wine_cont, Bench.select(:wine).distinct.where.not(wine: nil), :wine, :wine, {include_blank: true}, class: 'form-control' %>
            </div>
            <div class="col-3">
                <%= f.label "Graphics Card" %>
                <%= f.collection_select :gpu_cont, Bench.select(:gpu).distinct.where.not(gpu: nil), :gpu, :gpu, {include_blank: true}, class: 'form-control' %>
            </div>
        </div></p>
        <%= f.submit %>
        <% end %>
    </div>
</div>

<div class="card">
    <div class="card-header">
            <h3 class="card-title">Benchmarks</h3>
        <div class="card-tools">
        </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body p-0">
            <%= render partial: 'table', locals: {benchmarks: @benchmarks} %>
            <%= render 'checkboxes' %>
        </div>
    </div>

<div id="compareTable">
</div>
<div id="graphs">
    <%= render partial: 'graphs', locals: {benchmarks: @benchmarks.select(:game_id, :name, :id) } %> 
</div>


<%= render "checkboxes" %>
<script>
    // $.ajax("<%= stats_benches_path(benchmark_ids: @benchmarks.pluck(:id), type: "Renderer") %>")
</script>

app/views/benches/stats.js.erb
<% @benchmarks = Bench.where(id: params[:benchmark_ids]) %>
<% if params[:type] == "Wine" %>
    $('#graphs').html("<%= j render partial: 'benches/compare_graphs', locals: {benchmarks: @benchmarks.where(wine: @benchmarks.pluck(:wine)).group(:wine, :wine).joins(:inputs), type: params[:type]} %>")
    $('#compareTable').html("<%= j render partial: 'benches/compare_table', locals: {benchmarks: @benchmarks.pluck(:wine).uniq, type: params[:type]} %>")
<% end %>
<% if params[:type] == "Renderer" %>
    $('#graphs').html("<%= j render partial: 'benches/compare_graphs', locals: {benchmarks: @benchmarks.where(renderer: @benchmarks.pluck(:renderer)).joins(:inputs).group(:renderer, :renderer), type: params[:type]} %>")
    $('#compareTable').html("<%= j render partial: 'benches/compare_table', locals: {benchmarks: @benchmarks.pluck(:renderer).uniq, type: params[:type] } %>")
<% end %>