config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :games
  resources :benches, :path => "benchmarks" do
    collection do
      match 'stats' => 'benches#stats', via: [:get, :post], as: :stats
    end
  end
  resources :runs
  resources :traces do
    collection do
      match 'line_chart_amount' => 'traces#line_chart_amount', via: [:get], as: :line_chart_amount
    end
    member do
      get 'execution_time'
      get 'frames/:frame_id', to: 'traces#frames'
      post 'frames/:frame_id', to: 'traces#frames'
    end
    resources :trace_frames do
      resources :frame_outputs
    end
  end
  resources :static, only: [:index] do
    collection do
      get 'get_url'
      get 'get_ref_frames'
      post 'get_ref_frames'
    end
  end
  resources :users, only: [:edit, :show, :update, :index] do
    member do
      get 'edit_permissions'
    end
  end
  resources :gpus do
    member do
      get 'gpu_frames'
      get 'execution_time'
    end
    resources :frame_outputs
  end
  resources :frame_outputs do
    member do
      get 'history', to: 'frame_outputs#history'
    end
  end
  resources :games_tags, only: [:destroy]
  resources :bugs, only: [:create, :destroy, :index, :show, :update, :new] do
    member do
      post 'associate'
      post 'mark_fixed'
      post 're_open'
      get 'create_upstream_issue'
    end
    collection do
      match 'line_chart_amount' => 'bugs#line_chart_amount', via: [:get], as: :line_chart_amount
    end
  end
  resources :bugs_trace_frames, only: [:destroy]
  resources :jobs, only: [:destroy, :index, :show]
  resources :deduped_frame_outputs do
    member do
      post 'acceptable_frame'
      post 'unacceptable_frame'
      get 'frame_bug'
      get 'pre_merge_frame_bug'
      get 'issue'
      get 'next_frame'
      post 'dissociate'
    end
  end
  match 'stats' => 'static#stats', via: [:get], as: :stats
  resources :trace_execs
  resources :providers, only: [:destroy]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :graphics_apis
      match 'checksum' => 'static#checksum', via: [:get, :post], as: :checksum
      match 'image_checksum' => 'static#image_checksum', via: [:get, :post], as: :image_checksum
      match 'unoptimized_traces' => 'static#unoptimized_traces', via: [:get, :post], as: :unoptimized_traces
      match 'trace_lock' => 'static#trace_lock', via: [:get, :post], as: :trace_lock
      match 'frames_needing_review' => 'static#frames', via: [:get], as: :frames
      devise_scope :user do
        post 'login', to: 'sessions#create'
      end
      resources :traces do
        collection do
          match 'enrollment' => 'traces#enrollment', via: [:get], as: :enrollment
        end
      end
      resources :games
      resources :runs
      resources :jobs do
        resources :trace_execs
      end
      resources :trace_execs
      resources :gpus
      resources :users, only: [:index]
      resources :trace_compatibilities
      resources :commits
      resources :projects
      resources :benches
      resources :stats do
        collection do
          match 'frame_outputs' => 'stats#frame_outputs', via: [:get, :post], as: :frame_outputs
          get 'trace_frames/:id/' => 'stats#trace_frames', via: [:get], as: :trace_frames
          get 'blobs/:id/' => 'stats#blobs', via: [:get], as: :blobs
        end
      end
      resources :deduped_frame_outputs
    end
  end
  match "/-/profile", to: "users#profile", via: [:get], as: :profile
  match 'frames_needing_review' => 'static#frames', via: [:get], as: :frames
  match 'gpu_frames' => 'static#gpu_frames', via: [:get, :post], as: :gpu_frames
  root 'static#index'
end

app/models/trace.rb
class Trace < ApplicationRecord
    belongs_to :game
    has_many :trace_frames, dependent: :destroy
    has_one_attached :upload
    has_one_attached :optimized
    belongs_to :gpu, optional: true
    belongs_to :graphics_api, optional: true
    belongs_to :user, optional: true
    has_many :trace_compatibilities
    has_many :projects, -> { distinct }, through: :trace_compatibilities
    has_many :frame_outputs
    has_many :timelines, -> { distinct }, through: :frame_outputs
    has_many :deduped_frame_outputs, -> { distinct }, through: :frame_outputs
    has_many :trace_execs
    has_many :gpus, -> { distinct }, through: :trace_execs
    has_many :blobs, -> { select(:id, :service_name, :filename).distinct }, through: :upload_attachment
    accepts_nested_attributes_for :trace_frames

    TRACE_STATUS=["Traced", "Requires Tracing", "Requires GFXRecon Trace", "Tracing Failed"]

    def filename
        self.upload.filename.to_s
    end

    def self.filenames
        return Trace.includes(:blobs).pluck(:id, 'active_storage_blobs.filename').to_h
    end 

end

app/controllers/api/v1/traces_controller.rb
module Api
    module V1
        class TracesController < ApplicationController
            skip_forgery_protection
            before_action :can_download_trace, except: [:index, :show, :create, :update, :enrollment]
            before_action :can_upload_trace, only: [:create, :update], except: [:enrollment]
            before_action :authenticate_user!, except: [:show, :index]
            before_action :admin, only: [:enrollment]

            def index
                @traces = Trace.all.includes([:trace_frames, :graphics_api, :game, upload_attachment: :blob]).where(deleted: [nil, false])
                @pciid = params[:target_gpu_pciid]
                @gpu = Gpu.find_by(pciid: @pciid)
                @game = Game.where(appid: params[:steamid]).last if params[:steamid]
            end

            def create
                if current_user
                    @trace = Trace.new(trace_params)
                    @trace.user = current_user
                    if @trace.save
                        @trace.frames_to_capture.each do |i|
                            TraceFrame.create(frame_id: i, trace_id: @trace.id)
                        end
                    end
                    if @trace.errors.any?
                        render json: @trace.errors
                    else
                        render json: @trace
                    end
                end
            end

            def show
                @trace = Trace.find(params[:id])
                respond_to do |f|
                    f.json
                end
            end

            def update
                @trace = Trace.find(params[:id])
                @trace.update(trace_params)
                if @trace.errors.any?
                    render json: @trace.errors
                else
                    render json: @trace
                end
            end

            def enrollment
                @traces = Trace.where(graphics_api_id: nil)
                respond_to do |f|
                    f.json
                end
            end

            private
            def trace_params
                params.require(:trace).permit(:upload, :optimized, :gpuz, :game_id, :appid, :gpu_id, :optimize_lock, :graphics_api_id, metadata: {}, frames_to_capture: [])
            end

        end
    end
end

app/controllers/traces_controller.rb
class TracesController < ApplicationController
    before_action :authenticate_user!, except: [:line_chart_amount, :show, :index, :execution_time]
    before_action :can_upload_trace, only: [:create, :update, :edit]
    before_action :admin, only: [:destroy], except: [:update, :edit]

    def create
        @trace = Trace.new(trace_params)
        hash = {}
        hash["user"] = params[:user_metadata]
        @trace.metadata = hash
        @trace.user_id = current_user.id
        respond_to do |format|
            if @trace.save
                @trace.update(frames_to_capture: @trace.trace_frames.order(:frame_id).pluck(:frame_id))
                format.html { redirect_to @trace.game, notice: 'Trace was successfully created.' }
                format.json { render :edit, status: :created, location: @trace }
                format.js
            else
                format.html { redirect_to traces_path }
                format.json { render json: @trace.errors, status: :unprocessable_entity }
                format.js
            end
        end
    end

    def index
        @q = Trace.where(deleted: [nil, false]).ransack(params[:q])
        @traces = @q.result(distinct: true).page(params[:page]).per(10)
        @filenames = Trace.filenames
    end

    def destroy
        @trace = Trace.find(params[:id])
        @trace.update(deleted: true)
        # @trace.destroy
        redirect_to @trace.game
    end

    def edit
        @trace = Trace.find(params[:id])
    end

    def update
        @trace = Trace.find(params[:id])
        if @trace.update(trace_params)
            @trace.frames_to_capture.each do |i|
                TraceFrame.find_or_create_by(trace: @trace, frame_id: i)
            end
            @trace.trace_frames.each do |frame|
                if params[:trace]["frame_id_#{frame.frame_id}"] == "true"
                    array = @trace.frames_to_capture
                    array.delete(frame.frame_id)
                    @trace.update(frames_to_capture: array)
                end
            end
            redirect_to traces_path
        else
            redirect_to edit_trace_path(@trace)
        end
    end

    def show
        @trace = Trace.find(params[:id])
        @trace_frames = @trace.trace_frames.order(:frame_id)
        @gpus = Job.last.gpus.map {|gpu| gpu if !gpu.pciid.empty? }.compact
        @codenames = Gpu.codenames
        @timelines = @trace.timelines
    end

    def line_chart_amount
    end

    def execution_time
        @trace = Trace.find(params[:id])
        @timeline = JobTimeLine.find(params[:timeline]) if params[:timeline]
        @codenames = Gpu.codenames
        if @timeline
            @data = @trace.trace_execs.includes(:gpu, :timeline).
            where(status: 0, timeline: {id: @timeline.id}).where.not(
            execution_time: [0, nil, 0.0],
            gpu: {name: "{}"}).order(:id).group_by(&:gpu_id)
        else
            @data = @trace.trace_execs.includes(:gpu).
            where(status: 0).where.not(
            execution_time: [0, nil, 0.0],
            gpu: {name: "{}"}).order(:id).group_by(&:gpu_id)
        end
        respond_to do |format|
            format.json
        end
    end

    def frames
        @trace = Trace.find(params[:id])
        @frame = TraceFrame.find_by(frame_id: params[:frame_id])
        if @frame
            @q = @frame.latest_generated_frames.ransack(params[:q])
            @frames = @q.result(distinct: true).includes(:trace_exec)
            @timelines = JobTimeLine.where(id: @frames.pluck('jobs.timeline_id')).uniq
            @gpus = Gpu.where(id: @frames.pluck('trace_execs.gpu_id')).uniq
            @driver_branches = DriverBranch.where(id: @frames.map {|f| f.driver_branch.id}).uniq
        else
            render file: "#{Rails.root}/public/404.html", status: :not_found, layout: false
        end
    end

    private
    def trace_params
        params.require(:trace).permit(:upload, :gpuz, :game_id, :appid,
                                      :gpu_id, metadata: {}, frames_to_capture: [],
                                      trace_frames_attributes: [:id, :trace_id, :frame_id, :upload])
    end

end

app/views/traces/_deduped_table.html.erb
<div class="row">
  <div class="col-sm-12">
    <table class="table table-bordered">
      <thead>
      <th>GPU</th>
      <% @trace_frames.each do |trace_frame| %>
        <th><%= link_to trace_frame.frame_id, "/traces/#{@trace.id}/frames/#{trace_frame.frame_id}" %></th>
      <% end %>
      </thead>
      <tbody>
      <% if @trace_frames.first.upload.attached? %>
          <tr>
            <td>Reference frames</td>
            <% @trace_frames.with_attached_upload.each do |trace_frame| %>
              <td><%= link_to(image_tag(trace_frame.upload.variant(resize: '100x100')), trace_frame.upload) %></td>
            <% end %>
          <tr>
      <% end %>
          <% @gpus.each do |gpu| %>
          <tr>
            <td><%= gpu.name %></td>
            <% @trace_frames.each do |trace_frame| %>
              <% if @traceExec %>
                <% frame = @traceExec.frame_outputs.where(trace_frame: trace_frame).last %>
              <% else %>
                <% frame = Job.last.frame_outputs.where(trace_frame_id: trace_frame.id).includes(:trace_exec).where(
                  trace_execs: {gpu: gpu, trace: @trace}
                ).last %>
              <% end %>
              <% if frame.nil? %>
                <td class="text-center text-danger"><i class="fas fa-times fa-2x"></i></td>
              <% else %>
                  <% frame.upload.blob.update(content_type: "image/png") if !frame.upload.variable? and Rails.env.production? %>
                  <td> <%= link_to(image_tag(frame.upload.variant(resize: '100x100')), frame.deduped_frame_output, data: { turbolinks: false }) if Rails.env != "test" and Rails.env != "development" %></td>
              <% end %>
            <% end %>
          </tr>
          <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/traces/_form.html.erb
<%= form_for @trace, remote: true do |f| %>
    <script>
    function AddNewTraceFrame(){
        $.getScript("?trace_frame_count=" + trace_frame_count)
    }
    </script>
    <%= f.hidden_field :game_id, value: @game.id if params[:action] != "edit" %>
    <% @trace.trace_frames.each do |frame| %>
        <%= f.hidden_field "frame_id_#{frame.frame_id}", value: 0 %>
    <% end %>
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <%= f.label "GPU", :class => 'control-label' %>
                <div class="controls">
                    <%= f.collection_select :gpu_id, Gpu.where("metadata ? 'user'"), :id, :traced_gpu, {required: true}, class: 'form-control' %>
                </div>
            </div>
        </div>
    </div>
    </p>
    <div id="trace_frames">
    Trace frames
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Frame ID</th>
                    <th>Reference Frame</th>
                    <th>Destroy</th>
                <tr>
            </thead>
            <tbody id="trace_frames">
                <% if params[:action] == "edit" %>
                    <% @trace.trace_frames.each do |frame| %>
                        <tr>
                            <td><%= frame.frame_id %></td>
                            <td>
                            <% if Rails.env.production? %>
                                <a class="thumbnail" href="<%= frame.upload.url %>"><%= image_tag(frame.upload.blob.variant(resize: "50x50")) if frame.upload.blob.variable? %><span><%= image_tag(frame.upload.blob) %><br /></span></a>
                            <% end %>
                            </td>
                            <td>
                                <input type="checkbox" onclick="$('#trace_frame_id_' + <%= frame.frame_id %>).val(this.checked)" unchecked>
                            </td>
                        </tr>
                    <% end %>
                <% else %>
                    <%= render partial: 'traces/form_trace_frames', locals: {f: f, count: 0.to_s} %>
                <% end %>
            </tbody>
        </table>
    </div>
    <% if params[:action] != "edit" %>
    <button type="button" onclick="AddNewTraceFrame()" class="btn btn-primary">Add Trace Frame</button>
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <%= f.label "Trace", :class => 'control-label' %>
                <div class="controls">
                    <%= f.file_field :upload, required: true, direct_upload: true %>
                </div>
            </div>
        </div>
    </div>
    <% end %>
    <% if params[:action] == "edit" %>
        <%= f.submit "Submit", class: 'btn btn-success' %>
    <% else %>
        <%= f.submit "Upload", class: 'btn btn-success' %>
    <% end %>
<% end %>

app/views/traces/_form_trace_frames.html.erb
<tr>
    <%= f.fields_for :trace_frames do |f| %>
        <td><%= f.number_field :frame_id, required: true,
                id: "trace_trace_frames_attributes_" + count + "_frame_id",
                name: name="trace[trace_frames_attributes][" + count + "][frame_id]" %></td>
        <td><%= f.file_field :upload, required: true, direct_upload: true,
                id: "trace_trace_frames_attributes_" + count + "_upload",
                name: name="trace[trace_frames_attributes][" + count + "][upload]" %></td>
        <td><button onclick="$(this).closest('tr').remove();" class="btn btn-sm btn-primary">Remove Field</button></td>
    <% end %>
</tr>

app/views/traces/_review.html.erb
<div class="card">
    <div class="card-header">
        <h2 class="card-title">Frames</h2>
        <div class="card-tools">
            <% if current_user && current_user.can_download_trace? %>
                <%= link_to "Download trace", @trace.upload.url, class: "btn btn-primary" if Rails.env.production? %>
            <% end %>
        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body p-0 mb-">
        <%= render'deduped_table' %>
    </div>
</div>

app/views/traces/_search.html.erb
<%= search_form_for @q, remote: true do |f| %>
    <div class="row">
        <div class="col-3">
            <%= f.search_field :upload_blob_filename_cont, class: "form-control", placeholder: "Search trace name", onkeyup: "$('#submitBtn').trigger('click')" %>
        </div>
    </div>
    <div style="display:none">
        <%= f.submit "asdf", id: "submitBtn" %>
    </div>
<% end %>

app/views/traces/_table.html.erb
<div class="row">
  <div class="col-sm-12">
    <table class="table table-bordered">
      <thead>
        <th>Trace ID</th>
        <th>Trace</th>
        <th>Game</th>
        <% if current_user && current_user.can_download_trace? %>
          <th>Actions</th>
        <% end %>
      </thead>
      <tbody>
        <% @traces.includes(:game).order(:id).each do |trace| %>
        <tr>
            <td><%= link_to trace.id, trace %></td>
            <td><%= link_to @filenames[trace.id].to_s.truncate(40), trace %></td>
            <td><%= link_to trace.game.name, trace.game %></td>
            <% if current_user && current_user.can_download_trace? %>
              <td><%= link_to "Edit", edit_trace_path(trace), class: "btn btn-warning" %>
              <%= link_to "Download", trace.upload.url, class: "btn btn-success" if Rails.env.production? %>
              </td>
            <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/traces/_trace_frames_table.html.erb
<div class="row">
  <div class="col-sm-12">
    <table class="table table-bordered">
      <thead>
        <th>#</th>
        <th>Outputs</th>
          <!-- <th>Tools</th> -->
      </thead>
      <tbody>
        <% @trace.trace_frames.order(:id).each_with_index do |trace_frame, i| %>
        <tr>
            <td><%= link_to trace_frame.frame_id, trace_trace_frame_path(@trace, trace_frame) %></td>
            <td><%= trace_frame.frame_outputs.size %></td>
            <!-- <td>
              <%#= link_to "Destroy",
                  trace_path(trace_frame),
                  :method => :delete,
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-sm btn-danger', remote: false %>
            </td> -->
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/traces/_trace_link.html.erb
<%= link_to trace.upload.filename, trace %>

app/views/traces/create.js.erb
Turbolinks.visit()

app/views/traces/edit.html.erb
<%= render 'form' %>

app/views/traces/frames.html.erb
<% @timelines.each do |timeline| %>
    <div class="card">
        <div class="card-header">
            <h3 class="card-title"><%= timeline.to_s %></h3>
            <div class="card-tools">
            </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body p-0">
            <table class="table table-bordered">
                <thead>
                    <tr>
                    <th>GPUs \ Drivers</th>
                    <% @driver_branches.each do |branch| %>
                        <th><%= branch.driver.name %> / <%= branch.name %></th>
                    <% end %>
                    </tr>
                </thead>
                <tbody>
                    <% @gpus.each do |gpu| %>
                    <tr>
                        <td><%= gpu.name %></td>
                        <% @driver_branches.each do |branch| %>
                        <td>
                            <% frame = @frames.find_by(gpus: {id: gpu.id}, driver_branch: {id: branch.id}) %>
                            <% if frame.present? %>
                                <%= link_to(image_tag(frame.upload.variant(resize: '100x100')), history_frame_output_path(frame), data: { turbolinks: false }) %>
                            <% else %>
                                <span class="badge badge-danger" title="This gpu/timeline/driver_branch combination has not been seen">missing</span></h1>
                            <% end %>
                        </td>
                        <% end %>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
<% end %>

<script>
    function submitForm(){
        $('#frames_form').submit()
    }
</script>

app/views/traces/index.html.erb
<% content_for(:tabtitle, "Traces - Valve Dashboard") %>
<div class="card">
    <div class="card-header">
        <h3 class="card-title">Traces</h3>
        <div class="card-tools">
        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body p-0 mb-n3">
        <%= render 'search' %>
        <div id="tracesTable">
            <%= render 'table' %>
        </div>
    </div>
</div>
<div id="tracesPagination">
    <%= paginate @traces, theme: 'twitter-bootstrap-4' %>
</div>

app/views/traces/index.js.erb
$("#tracesTable").html("<%= j render 'traces/table' %>")
$("#tracesPagination").html("<%= j paginate @traces, theme: 'twitter-bootstrap-4' %>")

app/views/traces/show.html.erb
<% content_for(:tabtitle, "Trace: #{@trace.upload.filename} - Valve Dashboard") %>
<h3>Trace game: <%= @trace.game.name %></h3>
<h3>Trace name: <%= @trace.upload.filename %></h3>
<%= render 'review' %>

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Execution time over time</h3>
        <div class="card-tools">
        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body p-0">
      <%= select_tag 'timeline', options_for_select(@timelines.collect{ |t| [t.name, t.id] }), prompt: "All timelines", class: 'form-control col-3' %>
      <div id="chart-execution-time"></div>
    </div>
</div>
<script>
  Highcharts.chart('chart-execution-time', {});
  var chart = Highcharts.chart('chart-execution-time', {});

  function getChartData(timeline){
    var url = ""
    if (timeline)
      url = '/traces/10/execution_time?timeline=' + timeline
    else
      url = '/traces/10/execution_time'

    while (chart.series.length) {
      chart.series[0].remove();
    }

    Highcharts.ajax({
      url: url,
      success: function(data) {
        $.each(data.series, function (i) {
          chart.addSeries(data.series[i], true);
        });
        chart.update({
            title: {
                text: "",
                align: "center"
            },
            plotOptions: {
              series: {
                cursor: 'pointer',
                point: {
                  events: {
                    click: function (){
                      Turbolinks.visit("/trace_execs/" + this.exec_id)
                    }
                  }
                }
              }
            },
            tooltip: {
              formatter: function() {
                  var s = '<b>'+ moment(this.x).format('MMMM Do YYYY, h:mm:ss a') +'</b>';

                  $.each(this.points, function(i, point) {
                      s += '<br/><span style="color:' + point.color + '">\u25CF</span> ' + point.series.name + ': ' + Math.round(point.y * 10) / 10 + " seconds";
                  });

                  return s;
              },
              shared: true
            },
            xAxis: {
              title: {
                text: "Date",
              }
            },
            yAxis: {
              title: {
                text: "Execution time (seconds)"
              }
            },
          });
        }
    });
  }
  getChartData(0);
  $('#timeline').change(function() {
    getChartData($('#timeline').val())
  });
</script>